<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DataDrivenDemoSuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>7</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>cbacd9cb-f415-4e1c-97f8-53390f15407b</testSuiteGuid>
   <testCaseLink>
      <guid>3226f716-377e-44ae-b1f3-1562e401f5b6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Day3/DataDrivenDemo</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>57310dae-93a8-4f0b-a6c3-3ddbf64800a2</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/LoginTestData</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>57310dae-93a8-4f0b-a6c3-3ddbf64800a2</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>b430edae-4916-447e-a8de-9c9c6458f127</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>57310dae-93a8-4f0b-a6c3-3ddbf64800a2</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>1f2fd130-cfe1-4977-aea3-c4f4d707a4d5</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
